# All paths in this file are relative to the 'project_path' parameter defined inside *scripts_folder*/config/scripts_config.yaml
# Unless stated otherwise.
cmake_config:
  build_directory_name: build # Where will the CMake build files writen to
  directory_name: cmake/config # CMake project's configuration files are stored here
  config_files: # Relative to the above 'directory_name' cmake config directory
    dist_filename: config.cmake.dist # Contains CMake project variables definitions
    filename: config.cmake # This file will be created from the above, dist one. Include this one in your basic CMakeLists.txt to get access to those variables
  project:
    name: BasicCppSetup # CMake project 'PROJECT_NAME' variable will have this value
    version_major: '0' # CMake project 'PROJECT_VERSION_MAJOR' variable will have this value
    version_minor: '0' # CMake project 'PROJECT_VERSION_MINOR' variable will have this value
    version_patch: '1' # CMake project 'PROJECT_VERSION_PATCH' variable will have this value

    # The following are strings from 'cmake_config/config_files/dist_filename' file which will be replaced with the above values.
    # They appear in the file as '{placeholder}'
    name_placeholder: project_name
    version_major_placeholder: project_version_major
    version_minor_placeholder: project_version_minor
    version_patch_placeholder: project_version_patch

   # List of CMake targets
  targets:
    exe: # You can query target by this name via `beast <command>` commands
      name: project # How will CMake name this target
      name_placeholder: exe_target_name # This is the same as with 'cmake_config/project' variables

      # Per target configuration. It generally contains definition of target's include and source directories,
      # as well as list of header and source files this target will be using.
      # Can be omitted
      config_files:
        dist_filename: project/config.cmake.dist # This behaves similar to aforementioned general CMake config. Use it to define your target's variables and data
        filename: project/config.cmake

      # You can use this text file to save internal CMake variables' values into, in order to reference them from this config.
      # Can be omitted
      variables:
        target_cmake_variables_file_path_placeholder: project_cmake_vars_file_path # Placeholder as before
        target_cmake_variables_file_path: project/vars.txt # Path to the file with variables. Relative to 'cmake_config' directory

      # Contains information about target's include and source directories.
      directories:
        include_directory_placeholder: project_include_dir # Variable's value placeholder
        include_directory: '"${BasicCppSetup_SOURCE_DIR}/include"' # Target's include directory variable's value. The ${PROJECT_INCLUDE_DIR} will contain this value.
        source_directory_placeholder: project_src_dir # Variable's value placeholder
        source_directory: '"${BasicCppSetup_SOURCE_DIR}/src"'  # Target's source directory variable's value. The ${PROJECT_SRC_DIR} will contain this value.

       # You can reference variables from your vars.txt file here.
      headers:
        # The ${PROJECT_INCLUDE_DIR} variable is set inside `project/config.cmake` file. Its value must be saved into vars.txt file in order to resolved
        base_dir: "${PROJECT_INCLUDE_DIR}/Project" # Base directory added to every file from `files` list below.
        files_list_placeholder: project_headers # Placeholder for list of headers inside `project/config.cmake.dist` file.
        files: [] # Place your header files in here. Every file path MUST be relative to the `base_dir` directory.

      # You can reference variables from your vars.txt file here.
      sources:
        # The ${PROJECT_SRC_DIR} variable is set inside `project/config.cmake` file. Its value must be saved into vars.txt file in order to resolved
        base_dir: "${PROJECT_SRC_DIR}/Project" # Base directory added to every file from `files` list below.
        files_list_placeholder: project_sources # Placeholder for list of sources inside `project/config.cmake.dist` file.
        files: # Place your sources files in here. Every file path MUST be relative to the `base_dir` directory.
        - main.cpp

# The scripts included in 'scripts' directory will mirror all the `*.dist` files.
# If you want your CMake variables to be included in commit, place them in `*.dist` files on in `CMakeLists.txt` files.
# Files automatically generated from `*.dist` files are NOT included in the VCS.
# All of this is made for convenience of development, but can be skipped entirely.
# You can use pure CMake and Conan if you don't care about all this stuff.
# This config is only relevant for `beast <command>` commands.
# Use `config.yaml` for your development. This one's just an example.
